### ISSUE TITLE
tasks don't show up

### ISSUE THREAD

**Issue by mottiger** [osm-in/osm-tasking-manager2#13] opened 2018-08-08 22:40 UTC
Hi there

Thanks for the fix of the tasking manager.
The tasks won't show up to chose which one you want to do. I just can select 'random task'

Cheers

**Comment by answerquest** [comment] 2018-08-09 03:51
I just encountered the same problem. It did take quite some time to load up earlier, and I was wondering how we could put a "loading.." message on the page to indicate that. 

But this time it never loaded in even the simpler square-grid-line projects. After several minutes of waiting, i checked the console and found it has errored out:
Screenshot: [click here](https://i.imgur.com/7jnaEB0.jpg)

Text paste:
```
sammy-latest.min.js:8 [Thu Aug 09 2018 09:07:25 GMT+0530 (India Standard Time)] body 404 Not Found get /project/89  Error: 404 Not Found get /project/89 
    at n.Application.error (sammy-latest.min.js:8)
    at n.Application.notFound (sammy-latest.min.js:8)
    at n.Application.runRoute (sammy-latest.min.js:8)
    at n.Application._checkLocation (sammy-latest.min.js:8)
    at n.Application.run (sammy-latest.min.js:8)
    at Object.init (project.js:905)
    at HTMLDocument.<anonymous> (project.js:926)
    at i (jquery-1.12.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.3.min.js:2)
    at Function.ready (jquery-1.12.3.min.js:2)

jquery-1.12.3.min.js:4 GET http://tasks.openstreetmap.in/project/89/tasks.json 500 (Internal Server Error)
send @ jquery-1.12.3.min.js:4
ajax @ jquery-1.12.3.min.js:4
n.(anonymous function) @ jquery-1.12.3.min.js:4
createMap @ project.js:158
init @ project.js:870
(anonymous) @ project.js:926
i @ jquery-1.12.3.min.js:2
fireWith @ jquery-1.12.3.min.js:2
ready @ jquery-1.12.3.min.js:2
K @ jquery-1.12.3.min.js:2
```
On trying to access the URL I'm getting the same Internal Server Error page as earlier, but that may be by design:  
http://tasks.openstreetmap.in/project/89/tasks.json

**Comment by answerquest** [comment] 2018-08-23 10:00
Places in code where "tasks.json" is showing up:

- [osmtm/static/js/project.js#L159](https://github.com/osm-in/osm-tasking-manager2/blob/master/osmtm/static/js/project.js#L159)
- [`osmtm/__init__.py#L91`](https://github.com/osm-in/osm-tasking-manager2/blob/master/osmtm/__init__.py#L91)
- [osmtm/tests/test_project.py#L406 and L413](https://github.com/osm-in/osm-tasking-manager2/blob/master/osmtm/tests/test_project.py#L406)

**Comment by answerquest** [comment] 2018-09-07 04:25
@geohacker @batpad  just saw your instruction [elsewhere](https://github.com/osm-in/osm-tasking-manager2/issues/11#issuecomment-411442055) to tag you when opening a ticket. Could you look into this? What was solved a month back wasn't fully solved - there was a second error that we only found out about after the first error got fixed.

**Comment by geohacker** [comment] 2018-09-07 04:51
Thanks for the ping @answerquest and for the ticket @mottiger. This looks like it's because query to the database is failing at Django. It's unlikely that the versions are an issue, but will inspect.

```
[Fri Sep 07 06:43:29.599778 2018] [:error] [pid 14310] [remote 49.207.48.20:936]     cursor.execute(statement, parameters)
[Fri Sep 07 06:43:29.599809 2018] [:error] [pid 14310] [remote 49.207.48.20:936] ProgrammingError: (ProgrammingError) type "json" does not exist
[Fri Sep 07 06:43:29.599812 2018] [:error] [pid 14310] [remote 49.207.48.20:936] LINE 7:     , ST_AsGeoJSON(task.geometry, 5)::json As geometry
[Fri Sep 07 06:43:29.599815 2018] [:error] [pid 14310] [remote 49.207.48.20:936]                                               ^
```

**Comment by geohacker** [comment] 2018-09-07 12:43
This is fixed now. We had upgrade the PostgreSQL version from 9.1 to 9.6 on that server. http://tasks.openstreetmap.in/project/94

**Closed as completed by geohacker** 2018-09-07 12:43 UTC

**Comment by answerquest** [comment] 2018-09-08 13:42
Thats great! Thanks!
